site_name: Discovering Docker

# Repository - This creates the image in the top right corner that directs you to the code directory
#repo_name: DiscoveringDocker
#repo_url: https://github.com/rhit-mierowir/DiscoveringDocker




# Configuration
theme:
  name: material

  # Customization
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
  font:
    text: Roboto
    code: Roboto Mono
  
  features:
    # Useful Link: https://mrkeo.github.io/setup/setting-up-navigation/#table-of-contents
    # Defining how tabs behave
    #- navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky

    # Defining Navigation & Table Of Contents
    - toc.follow
    #- toc.integrate            # Not compatable with navigation.indexes  | I think this makes the left bar too crowded and discourages thuroughly describing text. It also obfuscates where files start and end.
    #- navigation.expand        #                                         | If included this auto-opens all tabs
    - navigation.indexes        # Not Compatable with toc.integrate       | This allows you to create index.md pages that you enter when you click on a group of pages
    #- navigation.tracking
    - navigation.instant        #                                         | This adjusts how the page loads to better handle large documentation blocks
    - navigation.top            #                                         | If you have a long file, this allows you to 

    # Search
    - search.highlight
    - search.share        # Lets you share your current search.
    - search.suggest
    
    # Content Settings
    - content.code.annotate
    - content.code.copy
    - content.tabs.link

# Plugins
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
      #prebuild_index: true #look into if this site gets really big.
  - awesome-nav
  - redirects: # https://github.com/mkdocs/mkdocs-redirects
      redirect_maps: {}
  - minify: 
      minify_html: true
  - git-revision-date-localized: #This creates the little markers on the bottom of the page for when it was last uploaded.
      enabled: true
      type: timeago
      enable_creation_date: true
      fallback_to_build_date: true

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: evolvablehardware
      repo: evolvablehardware.github.io
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true


# Extra
extra:
  generator: false #Get rid of "Made by MkDocs on the bottom of the page"
